[workspace]
authors = ["TiagoFilipeSousaGoncalves <tiago.galves@hotmail.com>"]
channels = ["conda-forge", "https://prefix.dev/conda-forge"]
name = "protocounterfactuals"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
# We need a python version that is compatible with pytorch
python = ">=3.11,<3.13"
tqdm = ">=4.67.1,<5"
pandas = ">=2.3.2,<3"
augmentor = ">=0.2.12,<0.3"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }
torchinfo = ">=1.8.0, <2"
scikit-learn = ">=1.7.2, <2"
wandb = ">=0.21.3, <0.22"
opencv-contrib-python-headless = ">=4.11.0.86, <5"

[target.osx.pypi-dependencies]
# OSX has no CUDA support so use the CPU here
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }
